#!/bin/bash

for f2 in dir2/* ; do
	x2=$(basename $f2)
    nothing=true
	for f1 in dir1/* ; do
		x1=$(basename $f1)
		if [[ $x1 == $x2 ]] ; then
			nothing=false
 			if [[ $f1 -ot $f2 ]] ; then
				echo "Updating $x1 ..."
				cp -f $f2 $f1
                break
			else
				echo "Nothing changed with $x1"
                break 
			fi	
		fi
	done
    if $nothing; then
    	echo "Copying $x2 ..."
    	cp -f $f2 dir1/
    fi
done	
	

	
	


